---
title: "11_3Dpred_SoleBoldo"
author: "BH"
date: "2023-03-09"
output: html_document
---

##Testing ScPred 3D ML models on Sole-Boldo datasets
```{r}
#MDA radial model
query <- NormalizeData(Sole_fibs2)
query <- scPredict(query, hdf_mda3D)

DimPlot(query, group.by = "SoleBoldo_name", label = FALSE, repel = TRUE, label.size=2, seed=123)  +
  custom_theme(base_size=20)


DimPlot(query, group.by = "scpred_prediction", label = FALSE, repel = TRUE, seed=123, cols = c("darkblue", "deeppink3", "antiquewhite4"))  +
  custom_theme(base_size=20)

ggsave(
  "UMAP_scpred_EPDS_3D.tiff",
  plot = last_plot(),
  device = "tiff",
  path = "../Output/SoleBoldo"
  )
```

## Investigating the percentage of DS predicted cells per age

```{r}
query2 <- query@meta.data
table <- table(query2[, c("age", "scpred_prediction")])
table
mat <- as.data.frame.matrix(table)
mat

percentages <- (mat/rowSums(mat))*100
percentages
percentages <- na.omit(percentages)
percentages
as.matrix(percentages)
percentages <- percentages[ order(row.names(percentages)), ]
v <- rownames(percentages)

barplot_data <- percentages$DS3D
barplot_names <- v

png(filename = "../Output/SoleBoldo/scPred3D_barplot_DS3Dbyage.png", width = 800, height = 600)  # Set appropriate width and height
barplot(barplot_data, names = barplot_names, cex.names = 0.7, col = "darkblue", main = "Percentage of predicted deeply senescent cells", xlab="Age",
         ylab = "Percentage", ylim = c(0, 100))
dev.off() 
```

```{r}
query2 <- query@meta.data
table <- table(query2[, c("age", "scpred_prediction")])
table
mat <- as.data.frame.matrix(table)
mat

percentages <- (mat/rowSums(mat))*100
percentages
percentages <- na.omit(percentages)
percentages
as.matrix(percentages)
percentages <- percentages[ order(row.names(percentages)), ]
v <- rownames(percentages)

barplot_data <- percentages$DS3D
barplot_names <- v

png(filename = "../Output/SoleBoldo/scPred3D_barplot_DS3Dbyage.png", width = 800, height = 600)  # Set appropriate width and height
barplot(barplot_data, names = barplot_names, cex.names = 0.7, col = "darkblue", main = "Percentage of predicted deeply senescent cells", xlab="Age",
         ylab = "Percentage", ylim = c(0, 100))
dev.off() 
```

```{r}
query2 <- query@meta.data
table <- table(query2[, c("SoleBoldo_name", "scpred_prediction")])
table
mat <- as.data.frame.matrix(table)
mat

percentages <- (mat/rowSums(mat))*100
percentages
percentages <- na.omit(percentages)
percentages
as.matrix(percentages)
percentages <- percentages[ order(row.names(percentages)), ]
v <- rownames(percentages)

barplot_data <- percentages$DS3D
barplot_names <- v

png(filename = "../Output/SoleBoldo/scPred3D_barplot_DS3Dbycellidentity.png", width = 800, height = 600)  # Set appropriate width and height
barplot(barplot_data, names = barplot_names, cex.names = 0.7, col = "darkblue", main = "Percentage of predicted deeply senescent cells", xlab="Cell Identity",
         ylab = "Percentage", ylim = c(0, 100))
dev.off() 
```

### Session information
```{r session_info_99}
sessionInfo()
```

This document was processed on: `r Sys.Date()`.
