---
title: "13_3Dpred_SoleBoldo"
author: "BH"
date: "2023-03-09"
output:
 pdf_document:
    toc: yes
---
```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r load_packages}
library("dplyr")
library("Seurat")
library("patchwork")
library("readxl")
library("tidyseurat")
library("ggplot2")
library("tidyverse")
library("RCurl")
library("cowplot")
library("sctransform")
library("scPred")
library("Seurat")
library("magrittr")
library("caret")
library("dplyr")
library("janitor")
library("factoextra")
library("reshape2")

options(future.globals.maxSize = 12000 * 1024^2)

```
# Testing ScPred 3D ML models on Sole-Boldo datasets
```{r}
custom_theme <- readRDS(file = "custom_theme.rds")
Sole_fibs2 <- readRDS(file="Sole_fibs2.rds")
hdf_mda3D <- readRDS(file="hdf_mda3D.rds")

#MDA radial model
querysole3D <- NormalizeData(Sole_fibs2)
querysole3D <- scPredict(querysole3D, hdf_mda3D)

DimPlot(querysole3D, group.by = "SoleBoldo_name", label = FALSE, repel = TRUE, label.size=2, seed=123)  +
  custom_theme(base_size=20)


DimPlot(querysole3D, group.by = "scpred_prediction", label = FALSE, repel = TRUE, seed=123, cols = c("darkblue", "deeppink3", "antiquewhite4"))  +
  custom_theme(base_size=20)

ggsave(
  "UMAP_scpred_EPDS_3D.tiff",
  plot = last_plot(),
  device = "tiff",
  path = "../Output/SoleBoldo"
  )
```

## Investigating the percentage of DS predicted cells per age

```{r}
query2 <- querysole3D@meta.data
table <- table(query2[, c("age", "scpred_prediction")])
table
mat <- as.data.frame.matrix(table)
mat

percentages <- (mat/rowSums(mat))*100
percentages
percentages <- na.omit(percentages)
percentages
as.matrix(percentages)
percentages <- percentages[ order(row.names(percentages)), ]
v <- rownames(percentages)

print(percentages)

percentages_solefibs3D <- percentages
write.csv(percentages_solefibs3D, "../Output/SoleBoldo/EPDS3D_solefibs.csv")

barplot_data <- percentages$DS3D
barplot_names <- v

png(filename = "../Output/SoleBoldo/scPred3D_barplot_DS3Dbyage.png", width = 800, height = 600)  # Set appropriate width and height
barplot(barplot_data, names = barplot_names, cex.names = 0.7, col = "darkblue", main = "Percentage of predicted deeply senescent cells", xlab="Age",
         ylab = "Percentage", ylim = c(0, 100))
dev.off() 
```

```{r}
query2 <- querysole3D@meta.data
table <- table(query2[, c("age", "scpred_prediction")])
table
mat <- as.data.frame.matrix(table)
mat

percentages <- (mat/rowSums(mat))*100
percentages
percentages <- na.omit(percentages)
percentages
as.matrix(percentages)
percentages <- percentages[ order(row.names(percentages)), ]
v <- rownames(percentages)

barplot_data <- percentages$DS3D
barplot_names <- v

png(filename = "../Output/SoleBoldo/scPred3D_barplot_DS3Dbyage.png", width = 800, height = 600)  # Set appropriate width and height
barplot(barplot_data, names = barplot_names, cex.names = 0.7, col = "darkblue", main = "Percentage of predicted deeply senescent cells", xlab="Age",
         ylab = "Percentage", ylim = c(0, 100))
dev.off() 
```

```{r}
query2 <- querysole3D@meta.data
table <- table(query2[, c("SoleBoldo_name", "scpred_prediction")])
table
mat <- as.data.frame.matrix(table)
mat

percentages <- (mat/rowSums(mat))*100
percentages
percentages <- na.omit(percentages)
percentages
as.matrix(percentages)
percentages <- percentages[ order(row.names(percentages)), ]
v <- rownames(percentages)

barplot_data <- percentages$DS3D
barplot_names <- v

png(filename = "../Output/SoleBoldo/scPred3D_barplot_DS3Dbycellidentity.png", width = 800, height = 600)  # Set appropriate width and height
barplot(barplot_data, names = barplot_names, cex.names = 0.7, col = "darkblue", main = "Percentage of predicted deeply senescent cells", xlab="Cell Identity",
         ylab = "Percentage", ylim = c(0, 100))
dev.off() 
```

```{r}
saveRDS(querysole3D, file="querysole3D.rds")
```

### Session information
```{r session_info_99}
sessionInfo()
```

This document was processed on: `r Sys.Date()`.
